### ISSUE TITLE
Backend:  create new User Service to support storing Analyses

### ISSUE THREAD

**Issue by steve-fischer-200** [VEuPathDB/EdaUserService#1]

**Comment by danicahelb** [comment]
discussed in 8/23/2021 EDA WG meeting

This is the only Phase 1 item not on track for late September release 

This is a backend task only; Ryan has begun to work on it, but genomics uniDB is his current priority. We aren't sure when he will have time to work on ClinEpi tasks.

There are many complications to releasing Phase 1 without this User Service in place

@steve-fischer-200 Could Ellie step in? This would delay the compute service for ~1 week

**Comment by ryanrdoherty** [comment]
All known Phase 1 functionality complete.

**Comment by danicahelb** [comment]
We will need to QA #392 and #448 to see that this is working properly.

**Comment by danicahelb** [comment]
I created analyses using qa.restricted on a chrome browser. I logged out, and was able to access the analyses after logging into qa.restricted on both safari and firefox.

I tried to create an analysis as a guest on qa.restricted on the chrome browser. I could see the analysis in "My analyses" when i was a guest. However, when I logged in as a user, this analysis did not get migrated over to my user account

**Comment by jtlong3rd** [comment]
> I created analyses using qa.restricted on a chrome browser. I logged out, and was able to access the analyses after logging into qa.restricted on both safari and firefox.
> 
> I tried to create an analysis as a guest on qa.restricted on the chrome browser. I could see the analysis in "My analyses" when i was a guest. However, when I logged in as a user, this analysis did not get migrated over to my user account

The "analysis migration" issue is actually a client concern, https://github.com/VEuPathDB/web-eda/issues/490, which has an outstanding PR.

**Comment by danicahelb** [comment]
yep, its fixed, thanks!
