### ISSUE TITLE
A 404 response is returned when the requested analysis belongs to a different user

### ISSUE THREAD

**Issue by dmfalke** [VEuPathDB/EdaUserService#34]
If a user requests an analysis that does not belong to them, the service returns a 404 response. A 403 would be more accurate. That would allow the frontend to tailor the error message for the user, including details about logging in, how to share, etc.

**Comment by ryanrdoherty** [comment]
Addressed with this commit: https://github.com/VEuPathDB/EdaUserService/commit/324b8268ee38ff569205770122e1c3782416116d
